name: card_hub
description: A Flutter package for animated credit/debit card displays in payment apps and digital wallets.
version: 0.2.0
repository: https://github.com/Abouassi98/card_hub
issue_tracker: https://github.com/Abouassi98/card_hub/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter


  # Images
  flutter_svg: ^2.1.0
  image: ^4.5.4

  # StateManagement & DI
  shared_preferences: ^2.5.3

  # Material Design
  material_color_utilities: ^0.11.0

 





dev_dependencies:
  flutter_test:
    sdk: flutter



  


  



import_sorter:
  comments: false


flutter:
  uses-material-design: true



  assets:
    - assets/images/cards/

  fonts: 
    - family: halter
      fonts:
        - asset: assets/fonts/halter.ttf