name: card_hub
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/Abouassi98/card_hub
issue_tracker: https://github.com/Abouassi98/card_hub/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter


  # Images
  flutter_svg: ^2.1.0
  image: ^4.2.0

  # StateManagement & DI
  
  freezed_annotation: ^2.4.1
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.5.3

 





dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints

  

  # Code gen
  build_runner: ^2.4.13
  freezed: ^2.4.8

  



import_sorter:
  comments: false


flutter:
  uses-material-design: true



  assets:
    - assets/images/cards/

  fonts: 
    - family: halter
      fonts:
        - asset: assets/fonts/halter.ttf