name: card_hub_test
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  card_hub:
    path: ../card_hub
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  # No additional dev dependencies needed currently.
# flutter:
#   fonts:
#     - family: Roboto
#       fonts:
#         - asset: assets/fonts/Roboto-Regular.ttf
#   assets:
#     - assets/images/

flutter:
  uses-material-design: true
